### ISSUE TITLE
Non-transparent plot background

### ISSUE THREAD

**Issue by aazuspan** [aazuspan/sankee#24]
The switch from `go.Figure` to `go.FigureWidget` to include interactive buttons caused an unintended side effect of changing plot background color from transparent to white. This is caused by an inconsistency between the two classes (see https://github.com/plotly/plotly.py/issues/3811).

If there's not a workaround or fix, we may just have to live with an opaque background. I guess there are worse things.

**Comment by aazuspan** [comment]
If I can inject some CSS, this is fixable with:

```css
.cell-output-ipywidget-background {
   background-color: transparent !important;
}
```

See https://github.com/microsoft/vscode-jupyter/issues/9403
